### PR TITLE
Binary SVM with SSG

### PR DESCRIPTION
**Pull request by tvogels**
I added BinarySVMWithSSG along the lines of BinarySVMWithDBCFW.
In the process, I found and fixed a bug in BinarySVMWithDBCFW, ignoring user specified *dissolveFunctions*.

### CODE REVIEW

**Comment by tvogels** [comment]
That was quick :p

-- 
Thijs Vogels

On 18 November 2015 at 00:11:16, Martin Jaggi (notifications@github.com) wrote:

Merged #36.

**Comment by martinjaggi** [comment]
though in the future we'd prefer not to have separate classes for all these. or at least, they should not duplicate the oracle/feature code for each optimizer

**Comment by tvogels** [comment]
Hm yeah, good point. Shall I factor those out to a separate class?
We could have a BinarySVM object that has the 'dissolveFunctions', or let the two classes inherit from an abstract BinarySVM class. What do you think?

-- 
Thijs Vogels

On 18 November 2015 at 00:14:13, Martin Jaggi (notifications@github.com) wrote:

though in the future we'd prefer not to have separate classes for all these. or at least, they should not duplicate the oracle/feature code for each optimizer

**Comment by martinjaggi** [comment]
yes, or just have a single class, since switching the optimizer is a one-line change anyway. i wonder what's easier for the user

**Comment by tvogels** [comment]
Yes. Although there are some slight differences. the Distributed BCFW needs an RDD, for example, and accepts an argument for minibatches yes or no. Maybe we should really split the 'model' and the 'optimizer'. Usage would be something like this:

val model: DissolveFunctions = BinarySVM; 
	(or your own dissolve functions, maybe we should have similar ones to pystruct: 
	 MultiLabelCrf, ChainCRF, GraphCRF, EdgeFeatureGraphCRF. 

val solver = DBCFWSolver(data, model, solverOptions, miniBatchEnabled = false)
val trainedModel = solver.optimize()

or
val solver = DBCFWSolver(model, options)  (why is miniBatchEnabled not a solverOption?)
val trainedModel = solver.train(data)


All the StructSVMWith* and BinarySVMWith* classes are not so complicated anyway. They could be moved to an 'examples' package. 

One more remark: I notice that the BCFW solvers output a pair (trainedModel, debugInfo), whereas SSGSolver just outputs trainedModel. 

I would be glad to help with this.

-- 
Thijs Vogels

On 18 November 2015 at 09:36:46, Martin Jaggi (notifications@github.com) wrote:

yes, or just have a single class, since switching the optimizer is a one-line change anyway. i wonder what's easier for the user

**Comment by martinjaggi** [comment]
yes, sth like
DissolveFunctions = BinarySVM
with many other possibilities would be perfect indeed. i wouldn't call it model though.

refacturing this would be great, but let's quickly check with @tribhuvanesh about it in the next days.
also, higher priority at the moment is still to explain the strange behavior in your modified chain example. not sure if it's easier to find that bug before or after refacturing...

and yes, miniBatchEnabled can become a solver-option

**Pull request merged**
